services:
  back-end:
    build: ./back-end
    expose:
      - "5252"

  front-end:
    build: ./front-end
    expose:
      - "9000"
    depends_on:
      - back-end

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end